# Generated by Django 4.0.6 on 2022-08-27 13:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendar_channel', '0002_event_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='UserEvents',
        ),
    ]
