# Generated by Django 5.0.1 on 2024-01-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_channel', '0006_userevents_hex_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevents',
            name='is_pined',
            field=models.BooleanField(default=False),
        ),
    ]
